### ISSUE TITLE
Request for different bpp prior training model weight files

### ISSUE THREAD

**Issue by godnn** [cambridge-mlg/RECOMBINER#1]
Dear Author, I was wondering if you could kindly provide the pretrained prior training model files on different bpps? I would like to compare your method with mine. I'd appreciate it if you could. Good luck with your research.

**Comment by jiajunhe98** [comment]
> Dear Author, I was wondering if you could kindly provide the pretrained prior training model files on different bpps? I would like to compare your method with mine. I'd appreciate it if you could. Good luck with your research.

Hi @godnn, thank you for reaching out! You can find the prior for CIFAR-10 at four different bpps at the following link. 
[https://drive.google.com/drive/folders/1EYr3T5NcTj0Ly7w56jcHXrG4KWzEwZJd?usp=drive_link](https://drive.google.com/drive/folders/1EYr3T5NcTj0Ly7w56jcHXrG4KWzEwZJd?usp=drive_link).
As I rerun these priors, there might be a slight difference compared to the results in the paper (based on my checks, these differences are negligible).

Please let me know if you need more help.

**Comment by godnn** [comment]
Thank you very much for your quick reply. I am trying to conduct a comparative experiment on the Kodak dataset. Could you please provide the relevant prior model weights?
Thank you very much!



---Original---
From: "Jiajun ***@***.***&gt;
Date: Tue, Dec 17, 2024 22:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cambridge-mlg/RECOMBINER] Request for different bpp priortraining model weight files (Issue #1)




  
Dear Author, I was wondering if you could kindly provide the pretrained prior training model files on different bpps? I would like to compare your method with mine. I'd appreciate it if you could. Good luck with your research.
  
Hi @godnn, thank you for reaching out! You can find the prior for CIFAR-10 at four different bpps at the following link.
 https://drive.google.com/drive/folders/1EYr3T5NcTj0Ly7w56jcHXrG4KWzEwZJd?usp=drive_link.
 As I rerun these priors, there might be a slight difference compared to the results in the paper (based on my checks, these differences are negligible).
 
Please let me know if you need more help.

**Comment by jiajunhe98** [comment]
Hi @godnn 
Unfortunately, I did not save the prior for the Kodak dataset. However, I do have the reconstructed Kodak images available at [https://drive.google.com/drive/folders/1sCW6LtDFa-Uba-0FTC8YeXjntTYPR8GO?usp=sharing](https://drive.google.com/drive/folders/1sCW6LtDFa-Uba-0FTC8YeXjntTYPR8GO?usp=sharing). 
The rate and corresponding average PSNR are as follows:

rate = [0.074, 0.178, 0.316, 0.488, 0.972] 

PSNR = [26.158,  28.594, 30.439, 31.953, 34.540]

Please let me know if this is sufficient for your needs.

**Comment by godnn** [comment]
Thank you for your reply. I am currently trying to train a modified KODAK dataset using RECOMBINER, so I would appreciate it if you could provide the weights of the prior model that was fully trained in your experiments. However, the information you have provided is also very helpful. At the moment, I am training the prior model using the DIV2K dataset.

Once again, I sincerely appreciate your kind assistance and I have great respect for your research work. I look forward to more exchanges in the future.





☆HAPPL☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cambridge-mlg/RECOMBINER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月18日(星期三) 凌晨2:30
***@***.***&gt;;
抄送:&nbsp;"cat ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cambridge-mlg/RECOMBINER] Request for different bpp prior training model weight files (Issue #1)





 
Hi @godnn
 Unfortunately, I did not save the prior for the Kodak dataset. However, I do have the reconstructed Kodak images available at https://drive.google.com/drive/folders/1sCW6LtDFa-Uba-0FTC8YeXjntTYPR8GO?usp=sharing.
 The rate and corresponding average PSNR are as follows:
 
rate = [0.074, 0.178, 0.316, 0.488, 0.972]
 
PSNR = [26.158,  28.594, 30.439, 31.953, 34.540]
 
Please let me know if this is sufficient for your needs.

**Comment by jiajunhe98** [comment]
@godnn Hi, I see. I will start to re-run some of the priors, but it might take some time due to quite limited GPU resources on my side. If possible, it would be great if you could run it with DIV2K on your end. Apologies for the inconvenience! Please don’t hesitate to let me know if you need anything further

**Comment by jiajunhe98** [comment]
Hi @godnn 
I re-run the prior for one bitrate (~0.32 bpp): [https://drive.google.com/drive/folders/1krspch-iLt5d2ji0BBpu1vrXbwai1VD6?usp=sharing](https://drive.google.com/drive/folders/1krspch-iLt5d2ji0BBpu1vrXbwai1VD6?usp=sharing). Hopefully this can help.

**Comment by godnn** [comment]
Thank you very much for your kind assistance. Your help has been very valuable to my research. Additionally, I suggest that you consider updating these weights on the RECOMBINER GitHub page, as I believe it could help many others.&nbsp;
I hope we can stay in touch, and once again, thank you!


Thank you very much for your kind assistance. Your help has been very valuable to my research. Additionally, I suggest that you consider updating these weights on the RECOMBINER GitHub page, as I believe it could help many others. I hope we can stay in touch, and once again, thank you!

☆HAPPL☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cambridge-mlg/RECOMBINER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月19日(星期四) 晚上9:05
***@***.***&gt;;
抄送:&nbsp;"cat ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cambridge-mlg/RECOMBINER] Request for different bpp prior training model weight files (Issue #1)





 
Hi @godnn
 I re-run the prior for one bitrate (~0.32 bpp): https://drive.google.com/drive/folders/1krspch-iLt5d2ji0BBpu1vrXbwai1VD6?usp=sharing. Hopefully this can help.

**Comment by jiajunhe98** [comment]
Thank you for your suggestions! I'll make the updates.
Best of luck with your research!


> Thank you very much for your kind assistance. Your help has been very valuable to my research. Additionally, I suggest that you consider updating these weights on the RECOMBINER GitHub page, as I believe it could help many others.&nbsp; I hope we can stay in touch, and once again, thank you! Thank you very much for your kind assistance. Your help has been very valuable to my research. Additionally, I suggest that you consider updating these weights on the RECOMBINER GitHub page, as I believe it could help many others. I hope we can stay in touch, and once again, thank you! ☆HAPPL☆ ***@***.*** &nbsp;
